"""Seaquest HF-expert retry: collect a raw_hf dataset in the ORIGINAL seaquest_ccrl schema,
generated by the validated Stage-S0/S0.5 HF CleanRL teacher (O-Sampled mode), NOT the scripted
policy. The ONLY scientific change vs the original collector is the action source.

Runs in the Stage-S0 `seaquest-s0:ocatari` Docker image (jax teacher + OCAtari coexist). Reuses:
  * the FROZEN Stage-S0 teacher adapter + port (teacher_port.SeaquestPort, common.load_teacher);
  * the ORIGINAL env's exact schema extraction (seaquest_gc._player_pos = bbox center,
    _oxygen = OxygenBar width) applied to the SAME OCAtari objects, and port.env.render() RGB.

Per pre-action decision step t, log (frame_t, action_t, player_pos_t, oxygen_t, target) — all the
SAME pre-action point — THEN step. Writes per-trajectory .npz in the original schema to
seaquest_ccrl/data/raw_hf/ plus a manifest. No masking here (the loader masks at load time).
The teacher does NOT condition on `target` (target is recorded for schema parity only).
"""
import sys, os, json, hashlib, argparse, subprocess
_REAL_STDOUT = sys.stdout                              # captured before teacher_port redirects stdout
def prog(*a, **kw):
    kw.pop("flush", None)
    print(*a, file=_REAL_STDOUT, flush=True, **kw)
import numpy as np

sys.path.insert(0, "/work")
sys.path.insert(0, "/work/seaquest_stage_s05")
import common as CM                                   # frozen S0 teacher loader + paths
from seaquest_ccrl import config as C
from seaquest_ccrl.envs.seaquest_gc import _player_pos, _oxygen   # EXACT original schema extraction

OUT_DEFAULT = "/work/seaquest_ccrl/data/raw_hf"


def _sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _sample_target(rng):
    x = rng.randint(C.TARGET_X_RANGE[0], C.TARGET_X_RANGE[1] + 1)
    y = rng.randint(C.TARGET_Y_RANGE[0], C.TARGET_Y_RANGE[1] + 1)
    return (float(x), float(y))


def collect(n_episodes, max_steps, base_seed, out_root, verbose=True):
    os.makedirs(out_root, exist_ok=True)
    from teacher_port import SeaquestPort                 # S0 frozen port
    teacher = CM.load_teacher("A")                        # S0 frozen adapter
    CM.prog = prog
    port = SeaquestPort(sticky=0.0, full_action_space=True, seed=base_seed)
    tgt_rng = np.random.RandomState(base_seed)            # target sampler (schema parity)
    noop_rng = np.random.RandomState(base_seed + 11)      # noop-reset RNG (S0.5 path)
    noise_rng = np.random.RandomState(base_seed + 777)    # uniform draws for frozen gumbel helper

    manifest = {
        "experiment": "seaquest_hf_expert_retry",
        "schema": ["frames(T,210,160,3)u8", "actions(T,)i64", "player_pos(T,2)f32",
                   "oxygen(T,)i32", "done(T,)bool", "target(T,2)f32", "theta-scalar"],
        "action_source": "HF CleanRL Seaquest expert (cand A), O-Sampled "
                         "(teacher.sample_action(gumbel_from_uniform(U), T=1)) via frozen S0 adapter",
        "teacher_ckpt": CM.CKPT, "teacher_ckpt_sha256": _sha256_file(CM.CKPT),
        "teacher_adapter_sha256": _sha256_file("/work/seaquest_stage_s0/teacher_adapter.py"),
        "teacher_port_sha256": _sha256_file("/work/seaquest_stage_s0/teacher_port.py"),
        "env": {"env_id": "ALE/Seaquest-v5 (OCAtari port)", "frameskip": SeaquestPort.FRAME_SKIP,
                "repeat_action_probability": 0.0, "full_action_space": True, "noop_max": 30,
                "teacher_obs": "(4,84,84) ALE-gray maxpool-last2 INTER_AREA"},
        "action_mapping": CM.ALE_MEANINGS,
        "schema_extraction": "player_pos = (Player.x+w/2, Player.y+h/2); oxygen = OxygenBar.w "
                             "(seaquest_gc._player_pos/_oxygen, original convention)",
        "target_note": "per-episode sampled from C.TARGET_*_RANGE for schema parity ONLY; "
                       "teacher does NOT condition on it",
        "frame_source": "port.env.render() rgb_array (210,160,3)",
        "theta": int(C.THETA), "oxy_mask_rect": list(C.OXY_MASK_RECT),
        "oxy_full_width": getattr(C, "OXY_FULL_WIDTH", None),
        "n_episodes_requested": n_episodes, "max_steps_per_ep": max_steps, "base_seed": base_seed,
        "episodes": [],
    }
    try:
        manifest["source_git_commit"] = subprocess.check_output(
            ["git", "-C", "/work", "rev-parse", "HEAD"]).decode().strip()
    except Exception:
        manifest["source_git_commit"] = None

    total = 0
    for ep in range(n_episodes):
        port.reset(seed=base_seed + ep, noop_max=30, rng=noop_rng)
        target = _sample_target(tgt_rng)
        frames, actions, positions, oxygens, dones, targets = [], [], [], [], [], []
        last_pos = last_oxy = None
        for t in range(max_steps):
            objs = [o for o in port.env.objects if getattr(o, "category", "") != "NoObject"]
            pos = _player_pos(objs); oxy = _oxygen(objs)
            if pos is None:
                pos = last_pos
            else:
                last_pos = pos
            if oxy is None:
                oxy = last_oxy
            else:
                last_oxy = oxy
            frame = np.asarray(port.env.render(), dtype=np.uint8)      # (210,160,3) PRE-action
            obs = port.teacher_obs()                                   # (4,84,84) teacher view
            noise = teacher.gumbel_from_uniform(noise_rng.uniform(size=(18,)))
            a = int(teacher.sample_action(obs, noise, temperature=1.0)[0])   # FROZEN O-Sampled

            frames.append(frame); actions.append(a)
            positions.append(pos if pos is not None else (np.nan, np.nan))
            oxygens.append(oxy if oxy is not None else -1)
            targets.append(target)

            rec = port.agent_step(a)
            done = bool(rec["terminated"] or rec["truncated"])
            dones.append(done)
            if done:
                break

        traj = {"frames": np.asarray(frames, dtype=np.uint8),
                "actions": np.asarray(actions, dtype=np.int64),
                "player_pos": np.asarray(positions, dtype=np.float32),
                "oxygen": np.asarray(oxygens, dtype=np.int32),
                "done": np.asarray(dones, dtype=np.bool_),
                "target": np.asarray(targets, dtype=np.float32),
                "theta": np.int32(C.THETA)}
        path = os.path.join(out_root, f"traj_{ep:04d}.npz")
        np.savez_compressed(path, **traj)
        manifest["episodes"].append({"file": os.path.basename(path), "steps": int(len(actions)),
                                     "sha256": _sha256_file(path),
                                     "ret_actions_distinct": int(len(set(actions))),
                                     "oxy_min": int(traj["oxygen"].min()), "oxy_max": int(traj["oxygen"].max())})
        total += len(actions)
        if verbose:
            prog(f"[ep {ep:03d}] steps={len(actions):4d} distinct_actions={len(set(actions))} "
                  f"oxy[{traj['oxygen'].min()}/{traj['oxygen'].max()}] -> {path}", flush=True)

    manifest["n_episodes"] = len(manifest["episodes"])
    manifest["n_transitions"] = total
    manifest["schema_matches_original_collector"] = True
    with open(os.path.join(out_root, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    prog(f"\nDONE: {len(manifest['episodes'])} trajectories, {total} steps -> {out_root}")
    return out_root


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--episodes", type=int, default=C.N_EPISODES)
    ap.add_argument("--max-steps", type=int, default=C.MAX_STEPS_PER_EP)
    ap.add_argument("--seed", type=int, default=C.SEED)
    ap.add_argument("--out", type=str, default=OUT_DEFAULT)
    args = ap.parse_args()
    collect(args.episodes, args.max_steps, args.seed, args.out)


if __name__ == "__main__":
    main()
